name: Fractalink
favicon: null
layout_spectrum: 0.70485
typography_spectrum: 0.74088
title: "India's best UX Design Studio"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4d600'
    - '#000000'
    - '#383e00'
    - '#495000'
    - '#b6c700'
  brandStrength: 0.22344392933882773
  lightness: 0.9289684391114861
  saturation: 0.8584343518596143
  rhythmicContrast: 0.331311312969774
purpose: []
